/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avroschema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Title extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Title\",\"namespace\":\"avroschema\",\"fields\":[{\"name\":\"title\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence title;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Title() {}

  /**
   * All-args constructor.
   */
  public Title(java.lang.CharSequence title) {
    this.title = title;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return title;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: title = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /** Creates a new Title RecordBuilder */
  public static avroschema.Title.Builder newBuilder() {
    return new avroschema.Title.Builder();
  }
  
  /** Creates a new Title RecordBuilder by copying an existing Builder */
  public static avroschema.Title.Builder newBuilder(avroschema.Title.Builder other) {
    return new avroschema.Title.Builder(other);
  }
  
  /** Creates a new Title RecordBuilder by copying an existing Title instance */
  public static avroschema.Title.Builder newBuilder(avroschema.Title other) {
    return new avroschema.Title.Builder(other);
  }
  
  /**
   * RecordBuilder for Title instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Title>
    implements org.apache.avro.data.RecordBuilder<Title> {

    private java.lang.CharSequence title;

    /** Creates a new Builder */
    private Builder() {
      super(avroschema.Title.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(avroschema.Title.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Title instance */
    private Builder(avroschema.Title other) {
            super(avroschema.Title.SCHEMA$);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'title' field */
    public java.lang.CharSequence getTitle() {
      return title;
    }
    
    /** Sets the value of the 'title' field */
    public avroschema.Title.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.title = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'title' field has been set */
    public boolean hasTitle() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'title' field */
    public avroschema.Title.Builder clearTitle() {
      title = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Title build() {
      try {
        Title record = new Title();
        record.title = fieldSetFlags()[0] ? this.title : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
